### ISSUE TITLE
Needs updating

### ISSUE THREAD

**Issue by fabiopedrosa** [ShinNoNoir/bson_lazy#1]
latest bson in incompatible with this lib. which version did you run it against?

**Comment by ShinNoNoir** [comment]
Hmm, I haven't used or worked on this in a long while, but based on setup.py it was most likely tested against PyMongo 2.5.

**Comment by wolph** [comment]
Seems broken indeed: https://travis-ci.org/ShinNoNoir/bson_lazy/jobs/6292043

**Comment by ShinNoNoir** [comment]
It seems fixing this might take some time. I thought, maybe changing `ZERO = bson.ZERO` to `ZERO = b"\x00"` would fix it, but there are more issues that need some fixing...

**Comment by fabiopedrosa** [comment]
I tried that quick change as well, but there's a couple more changes that need to be address. I ended up downgrading pymongo for now.

**Comment by wolph** [comment]
I've just tried to change the `uuid_subtype` to match the new protocol but that still appears to break stuff:

```
uuid_subtype = bson.CodecOptions(uuid_representation=bson.OLD_UUID_SUBTYPE)
```
